package com.mindtrace.ai.database.entity;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.Index;
import androidx.room.PrimaryKey;

/**
 * Represents a single AI-generated intervention task.
 *
 * <p>Tasks are generated by {@code InterventionEngine} based on the user's
 * current {@code RiskClassification}, {@code CrisisLevel}, and behavioral
 * signals. Each task is linked to its triggering risk category and includes
 * a human-readable explanation of why it was generated.</p>
 *
 * <h3>Task Lifecycle:</h3>
 * <pre>
 *   PENDING → ACTIVE → COMPLETED / SKIPPED / EXPIRED / SNOOZED
 *                        ↓ (on complete)
 *                   effectivenessRating prompt
 *                        ↓
 *                   pre/post mood capture
 *                        ↓
 *                   XP reward credited
 * </pre>
 *
 * <h3>Indexing Strategy:</h3>
 * <ul>
 *   <li>{@code dateCreated} — for chronological ordering</li>
 *   <li>{@code status} — for active/completed/expired filtering</li>
 *   <li>{@code category} — for category-filtered views</li>
 *   <li>{@code linkedRiskCategory} — for risk-linked analytics</li>
 * </ul>
 *
 * @see com.mindtrace.ai.ai.InterventionEngine
 * @see com.mindtrace.ai.database.dao.TaskDao
 */
@Entity(
        tableName = "intervention_tasks",
        indices = {
                @Index(value = {"dateCreated"}),
                @Index(value = {"status"}),
                @Index(value = {"category"}),
                @Index(value = {"linkedRiskCategory"}),
                @Index(value = {"observationWindowEnd"})
        }
)
public class InterventionTask {

    /** 2-hour observation window duration in milliseconds. */
    public static final long OBSERVATION_WINDOW_MS = 2L * 60 * 60 * 1000;

    @PrimaryKey(autoGenerate = true)
    public int id;

    // ─────────────────────────────────────────────────────────────────────
    // CORE — Original fields (backward compatible)
    // ─────────────────────────────────────────────────────────────────────

    /** When this task was created by the InterventionEngine. */
    public long dateCreated;

    /** Task title (e.g., "Mindful Breathing", "Digital Detox"). */
    public String title;

    /** Detailed description of what the user should do. */
    public String description;

    /**
     * Task category for grouping and filtering.
     * Values: Mindfulness, Journaling, Social, Purpose, Detox, Recovery, Focus
     */
    public String category;

    /** Estimated duration in minutes. */
    public int durationMinutes;

    /**
     * @deprecated Use {@link #status} instead. Kept for migration compatibility.
     */
    @Deprecated
    public boolean isCompleted;

    /**
     * @deprecated Use {@link #status} instead. Kept for migration compatibility.
     */
    @Deprecated
    public boolean isSkipped;

    /** Timestamp when the task was completed. 0 if not yet completed. */
    public long completedAt;

    /** Timestamp when the task was skipped. 0 if not yet skipped. */
    public long skippedAt;

    // ─────────────────────────────────────────────────────────────────────
    // PRIORITY & DIFFICULTY — Adaptive task calibration
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Priority level (1=lowest, 5=highest).
     * Crisis-triggered tasks default to 5; routine tasks to 2-3.
     */
    @ColumnInfo(defaultValue = "3")
    public int priority;

    /**
     * Difficulty level as a string enum.
     * Values: "EASY", "MEDIUM", "HARD"
     * Used for adaptive difficulty calibration based on user completion history.
     */
    @ColumnInfo(defaultValue = "EASY")
    @NonNull
    public String difficulty = "EASY";

    // ─────────────────────────────────────────────────────────────────────
    // SOURCE & LINKAGE — What triggered this task
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Which AI signal triggered this task generation.
     * Values: "classification", "crisis", "anomaly", "behavior", "check_in", "manual"
     */
    @Nullable
    @ColumnInfo(defaultValue = "check_in")
    public String sourceTag;

    /**
     * The risk category this task addresses.
     * Values: "digital_addiction", "stress_anxiety", "depression",
     *         "social_isolation", "sleep_disruption", "low_fulfilment", "general"
     */
    @Nullable
    @ColumnInfo(defaultValue = "general")
    public String linkedRiskCategory;

    /**
     * Human-readable explanation of why this task was generated.
     * Example: "Your stress score is elevated (72%) and sleep quality dropped — breathing helps."
     */
    @Nullable
    public String whyThisTask;

    // ─────────────────────────────────────────────────────────────────────
    // SCHEDULING — Time-aware task delivery
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Preferred time slot for this task.
     * Values: "MORNING", "AFTERNOON", "EVENING", "ANYTIME"
     */
    @ColumnInfo(defaultValue = "ANYTIME")
    @NonNull
    public String scheduledTimeSlot = "ANYTIME";

    /**
     * When this task expires (auto-expire after 24h by default).
     * 0 means no expiry.
     */
    @ColumnInfo(defaultValue = "0")
    public long expiresAt;

    /**
     * If snoozed, when the task becomes active again.
     * 0 means not snoozed.
     */
    @ColumnInfo(defaultValue = "0")
    public long snoozedUntil;

    // ─────────────────────────────────────────────────────────────────────
    // LIFECYCLE — Task state machine
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Current task status (replaces isCompleted/isSkipped booleans).
     * Values: "PENDING", "ACTIVE", "COMPLETED", "SKIPPED", "EXPIRED", "SNOOZED"
     */
    @ColumnInfo(defaultValue = "ACTIVE")
    @NonNull
    public String status = "ACTIVE";

    // ─────────────────────────────────────────────────────────────────────
    // EFFECTIVENESS — Post-completion feedback
    // ─────────────────────────────────────────────────────────────────────

    /**
     * User's effectiveness rating after completion (0=not rated, 1-5 stars).
     * Used to build per-user effectiveness profiles.
     */
    @ColumnInfo(defaultValue = "0")
    public int effectivenessRating;

    /**
     * User's mood before starting the task (e.g., "Anxious", "Sad", "Neutral").
     * Null if not captured.
     */
    @Nullable
    public String preCompletionMood;

    /**
     * User's mood after completing the task.
     * Null if not captured. Compared with preCompletionMood for effectiveness analysis.
     */
    @Nullable
    public String postCompletionMood;

    // ─────────────────────────────────────────────────────────────────────
    // GAMIFICATION — XP, streaks, engagement
    // ─────────────────────────────────────────────────────────────────────

    /**
     * XP points awarded on completion.
     * EASY=10, MEDIUM=25, HARD=50, crisis=75.
     */
    @ColumnInfo(defaultValue = "10")
    public int xpReward;

    // ─────────────────────────────────────────────────────────────────────
    // MICRO-INTERVENTION — 2-min emergency tasks
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Whether this is a micro-intervention (2-min emergency task).
     * Generated when CrisisLevel >= ELEVATED.
     */
    @ColumnInfo(defaultValue = "0")
    public boolean isMicroIntervention;

    // ─────────────────────────────────────────────────────────────────────
    // TASK SEQUENCES — Multi-step chains
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Sequence group ID — tasks with the same sequenceId form a chain.
     * Null if standalone task.
     */
    @Nullable
    public String sequenceId;

    /**
     * Order within the sequence (1-based). 0 if standalone.
     */
    @ColumnInfo(defaultValue = "0")
    public int sequenceOrder;

    // ─────────────────────────────────────────────────────────────────────
    // OBSERVATION WINDOW — Post-intervention efficacy tracking
    // ─────────────────────────────────────────────────────────────────────

    /**
     * End timestamp of the 2-hour observation window.
     * Set to {@code completedAt + 2h} when the task is completed.
     * 0 means no observation window is active.
     *
     * <p>During this window, the system captures a post-intervention
     * risk classification to compute efficacy. The window is checked
     * by the periodic UsageWorker and by EfficacyWorker.</p>
     */
    @ColumnInfo(defaultValue = "0")
    public long observationWindowEnd;

    /**
     * Overall risk score captured at the moment the task was started/created.
     * Used as the "before" measurement for efficacy computation.
     * 0.0 means not captured (legacy tasks).
     */
    @ColumnInfo(defaultValue = "0")
    public float preInterventionRisk;

    /**
     * Overall risk score captured after the observation window closes.
     * Used as the "after" measurement for efficacy computation.
     * 0.0 means not yet measured or observation window still open.
     */
    @ColumnInfo(defaultValue = "0")
    public float postInterventionRisk;

    /**
     * Computed efficacy score: {@code preInterventionRisk - postInterventionRisk}.
     * Positive = intervention helped (risk decreased).
     * Negative = risk increased after intervention.
     * 0.0 = not yet computed or no change.
     *
     * <p>Range: typically -1.0 to 1.0. Computed by
     * {@link com.mindtrace.ai.ai.InterventionEngine#computeTaskEfficacy}.</p>
     */
    @ColumnInfo(defaultValue = "0")
    public float efficacyScore;

    // ─────────────────────────────────────────────────────────────────────
    // CONVENIENCE METHODS
    // ─────────────────────────────────────────────────────────────────────

    /** Check if the task is currently actionable. */
    public boolean isActionable() {
        if ("COMPLETED".equals(status) || "SKIPPED".equals(status) || "EXPIRED".equals(status)) {
            return false;
        }
        if ("SNOOZED".equals(status) && snoozedUntil > System.currentTimeMillis()) {
            return false;
        }
        if (expiresAt > 0 && System.currentTimeMillis() > expiresAt) {
            return false;
        }
        return true;
    }

    /** Check if the task has expired. */
    public boolean hasExpired() {
        return expiresAt > 0 && System.currentTimeMillis() > expiresAt
                && !"COMPLETED".equals(status) && !"SKIPPED".equals(status);
    }

    /** Check if the task is snoozed and the snooze period is still active. */
    public boolean isSnoozed() {
        return "SNOOZED".equals(status) && snoozedUntil > System.currentTimeMillis();
    }

    /** Mark as completed with timestamp and start the 2-hour observation window. */
    public void markCompleted() {
        this.status = "COMPLETED";
        this.isCompleted = true;
        this.completedAt = System.currentTimeMillis();
        this.observationWindowEnd = this.completedAt + OBSERVATION_WINDOW_MS;
    }

    /** Mark as skipped with timestamp. */
    public void markSkipped() {
        this.status = "SKIPPED";
        this.isSkipped = true;
        this.skippedAt = System.currentTimeMillis();
    }

    /** Mark as expired. */
    public void markExpired() {
        this.status = "EXPIRED";
    }

    /** Snooze for the given duration in milliseconds. */
    public void snooze(long durationMs) {
        this.status = "SNOOZED";
        this.snoozedUntil = System.currentTimeMillis() + durationMs;
    }

    /** Get XP based on difficulty if xpReward not explicitly set. */
    public int getEffectiveXp() {
        if (xpReward > 0) return xpReward;
        if (isMicroIntervention) return 75;
        switch (difficulty) {
            case "HARD": return 50;
            case "MEDIUM": return 25;
            default: return 10;
        }
    }

    /** Whether the user provided an effectiveness rating. */
    public boolean hasEffectivenessRating() {
        return effectivenessRating > 0;
    }

    /** Whether pre/post mood was captured for effectiveness analysis. */
    public boolean hasMoodCapture() {
        return preCompletionMood != null && postCompletionMood != null;
    }

    /** Whether this task is part of a sequence. */
    public boolean isPartOfSequence() {
        return sequenceId != null && !sequenceId.isEmpty();
    }

    /** Whether this task has an active observation window that hasn't closed yet. */
    public boolean isObservationWindowActive() {
        return observationWindowEnd > 0 && System.currentTimeMillis() < observationWindowEnd;
    }

    /** Whether the observation window has closed and efficacy can be computed. */
    public boolean isObservationWindowClosed() {
        return observationWindowEnd > 0 && System.currentTimeMillis() >= observationWindowEnd;
    }

    /** Whether efficacy has already been computed for this task. */
    public boolean hasEfficacyScore() {
        return postInterventionRisk > 0f || efficacyScore != 0f;
    }

    /** Set the pre-intervention risk snapshot. */
    public void capturePreInterventionRisk(float currentRisk) {
        this.preInterventionRisk = currentRisk;
    }

    /**
     * Finalize the observation window with a post-intervention risk reading.
     * Computes and stores the efficacy score.
     */
    public void finalizeObservation(float postRisk) {
        this.postInterventionRisk = postRisk;
        this.efficacyScore = this.preInterventionRisk - postRisk;
    }

    /** Get a display-friendly difficulty label. */
    @NonNull
    public String getDifficultyLabel() {
        switch (difficulty) {
            case "HARD": return "Challenging";
            case "MEDIUM": return "Moderate";
            default: return "Quick & Easy";
        }
    }

    /** Get a display-friendly status label. */
    @NonNull
    public String getStatusLabel() {
        switch (status) {
            case "COMPLETED": return "✓ Done";
            case "SKIPPED": return "Skipped";
            case "EXPIRED": return "Expired";
            case "SNOOZED": return "Snoozed";
            case "PENDING": return "Upcoming";
            default: return "Active";
        }
    }

    /** Get category icon emoji. */
    @NonNull
    public String getCategoryIcon() {
        if (category == null) return "📋";
        switch (category.toLowerCase()) {
            case "mindfulness": return "🧘";
            case "journaling": return "📝";
            case "social": return "👥";
            case "purpose": return "🎯";
            case "detox": return "📵";
            case "recovery": return "🌿";
            case "focus": return "🔍";
            default: return "📋";
        }
    }

    @NonNull
    @Override
    public String toString() {
        return "InterventionTask{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", category='" + category + '\'' +
                ", status='" + status + '\'' +
                ", priority=" + priority +
                ", difficulty='" + difficulty + '\'' +
                ", xp=" + getEffectiveXp() +
                ", linked='" + linkedRiskCategory + '\'' +
                '}';
    }
}
